package com.example.demo.enums;

public enum EventAddress {

    GET_ALL_USER, GET_USER_BY_ID, INSERT_USER, UPDATE_USER, DELETE_USER,
    GET_USER_VERSION_BY_USER_ID, INSERT_USER_VERSION, GET_ALL_USER_VERSION, DELETE_VERSION_BY_USER_ID
}
